window.showScreen = window.showScreen || function(name) {
  const ids = {menu:"homeScreen", news:"newsApp", dispatch:"dispatchApp", dcinside:"dcApp", story:"storyApp", kakao:"kakaoApp", notification:"notificationApp", everytime:"everytimeApp", gpt:"gptApp", google:"googleApp", googleResults:"googleResultsApp", instagram:"instagramApp", instagramDm:"instagramDmApp", twitter:"twitterApp", naver:"naverApp", naverBlog:"naverBlogApp", naverSearch:"naverSearchApp", youtube:"youtubeApp", netflix:"netflixApp", tinder:"tinderApp", discord:"discordApp"};
  Object.keys(ids).forEach(k => {
    const el = document.getElementById(ids[k]);
    if (el) el.classList.toggle("hidden", k !== name);
  });
  try { sessionStorage.setItem("virtual_source_screen", name); } catch(e) {}
};

function toggleHomeCategory(btn){
  const category=btn.closest('.home-category');
  if(!category) return;
  const open=!category.classList.contains('open');
  document.querySelectorAll('.home-category.open').forEach(el=>{el.classList.remove('open'); const b=el.querySelector('.home-category-main'); if(b){b.setAttribute('aria-expanded','false'); const a=b.querySelector('.home-category-arrow'); if(a)a.textContent='＋';}});
  if(open){category.classList.add('open');btn.setAttribute('aria-expanded','true');const a=btn.querySelector('.home-category-arrow');if(a)a.textContent='－';}
}

const REACTION_SPRITE = "이미지/img-ba868ac486f5.webp";
const PLACEHOLDER_IMG = "data:image/svg+xml;utf8," + encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' width='800' height='450'><rect width='100%' height='100%' fill='%23e2e2e2'/></svg>");
const PLACEHOLDER_AVATAR = "data:image/svg+xml;utf8," + encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><rect width='100%' height='100%' fill='%23ddd'/></svg>");
const CATEGORIES = ["정치","경제","사회","엔터","생활/문화","IT/과학","세계"];
const STORAGE_KEY = "virtual_news_draft_v1";
const DEFAULT_STATE = {category:"사회",outlet:"가상일보",outletAvatar:PLACEHOLDER_AVATAR,outletLogo:null,title:"제목을 입력하세요",date:(()=>{const d=new Date();return `${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,"0")}.${String(d.getDate()).padStart(2,"0")}.`;})(),time:"오후 12:22",likeCount:"8",commentCount:"40",img:null,body:"여기에 기사 본문을 입력하세요.\n\n굵게 하고 싶은 부분은 드래그한 뒤 위 'B 굵게' 버튼을 누르세요.",view:"mobile",reactions:{like:"16",cheer:"19",congrats:"406",expect:"5",surprise:"215",sad:"11"},commentTotal:"103",commentActive:"98",commentDeleted:"5",commentViolation:"0",comments:[{avatar:null,nick:"user****",date:"2026.09.07. 11:23",body:"댓글 내용을 입력하세요.",image:null,likes:"0"},{avatar:null,nick:"user****",date:"2026.09.07. 11:20",body:"댓글 내용을 입력하세요.",image:null,likes:"0"}],extraOpen:true};
let state=loadState();
function cloneDefault(){return JSON.parse(JSON.stringify(DEFAULT_STATE));}
function loadState(){try{const raw=sessionStorage.getItem(STORAGE_KEY);if(raw)return Object.assign(cloneDefault(),JSON.parse(raw));}catch(e){}return cloneDefault();}
function saveState(){try{sessionStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
function escHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function renderBody(raw){const paragraphs=raw.split(/\n{2,}/).filter(p=>p.trim().length>0);return paragraphs.map(p=>{let escaped=escHtml(p).replace(/\n/g,"<br/>");escaped=escaped.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");return "<p>"+escaped+"</p>";}).join("\n");}
function formatDate(dateStr,timeStr){return [dateStr,timeStr].filter(Boolean).join(" ");}
const REACTION_META=[{key:"like",emoji:"😍",label:"좋아요"},{key:"cheer",emoji:"😆",label:"응원해요"},{key:"congrats",emoji:"🥳",label:"축하해요"},{key:"expect",emoji:"😮",label:"기대해요"},{key:"surprise",emoji:"😱",label:"놀랐어요"},{key:"sad",emoji:"😢",label:"슬퍼요"}];
function renderReactions(){const positions=["0%","20%","40%","60%","80%","100%"];const html=`<div class="reaction-grid">`+REACTION_META.map((r,i)=>`<div class="reaction-item"><div class="reaction-image" style="--reaction-sprite: url('${REACTION_SPRITE}'); background-position-x: ${positions[i]};" aria-label="${r.label}"></div><div class="reaction-count">${escHtml(state.reactions[r.key]??"0")}</div></div>`).join("")+`</div>`;document.querySelectorAll("[data-reaction-section]").forEach(el=>el.innerHTML=html);}
function renderComments(){const comments=state.comments||[];const commentHtml=comments.map(c=>`<div class="comment-item"><div class="comment-top"><img class="comment-avatar" src="${c.avatar||PLACEHOLDER_AVATAR}" /><div><div class="comment-nick">${escHtml(c.nick||"user****")}</div><div class="comment-date">${escHtml(c.date||"")}</div></div></div><div class="comment-body">${escHtml(c.body||"").replace(/\n/g,"<br/>")}</div><span class="comment-reply-btn">답글</span></div>`).join("");const html=`<div class="comment-header"><div class="comment-total">${escHtml(state.commentTotal)}개의 댓글</div></div><div class="comment-stats">현재 댓글 <b>${escHtml(state.commentActive)}</b> &nbsp;|&nbsp; 작성자 삭제 <b>${escHtml(state.commentDeleted)}</b> &nbsp;|&nbsp; 규정 미준수 <b>${escHtml(state.commentViolation)}</b></div><div class="comment-sort">최신순</div>${commentHtml}`;document.querySelectorAll("[data-comment-section]").forEach(el=>el.innerHTML=html);}
function renderExtraToggle(){document.querySelectorAll("[data-extra-panel]").forEach(el=>el.classList.toggle("open",!!state.extraOpen));document.querySelectorAll("[data-extra-toggle]").forEach(el=>el.textContent=state.extraOpen?"감정표현 · 댓글 접기 ▴":"감정표현 · 댓글 보기 ▾");}
function renderTabsInto(el){el.innerHTML=CATEGORIES.map(c=>`<div class="tab${c===state.category?" active":""}">${c}</div>`).join("");}
function renderAll(){document.querySelectorAll("[data-tabs]").forEach(renderTabsInto);document.querySelectorAll("[data-title]").forEach(el=>el.textContent=state.title);document.querySelectorAll("[data-date]").forEach(el=>el.textContent="입력 "+formatDate(state.date,state.time));document.querySelectorAll("[data-like]").forEach(el=>el.textContent=state.likeCount);document.querySelectorAll("[data-comment]").forEach(el=>el.textContent=state.commentCount);document.querySelectorAll("[data-outlet-logo]").forEach(el=>{if(state.outletLogo){el.src=state.outletLogo;el.classList.remove("hidden");}else{el.src="";el.classList.add("hidden");}});document.querySelectorAll("[data-img]").forEach(el=>{if(state.img){el.src=state.img;el.classList.remove("hidden");}else{el.src="";el.classList.add("hidden");}});document.querySelectorAll("[data-body]").forEach(el=>el.innerHTML=renderBody(state.body));renderReactions();renderComments();renderExtraToggle();saveState();}
function bindInput(id,key,evt){const el=document.getElementById(id);if(!el)return;el.addEventListener(evt||"input",e=>{state[key]=e.target.value;renderAll();});}
function fillFormFromState(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v;};const preview=document.getElementById("outletLogoPreview");if(preview)preview.src=state.outletLogo||"";set("title",state.title);set("date",state.date);set("time",state.time);set("likeCount",state.likeCount);set("commentCount",state.commentCount);set("body",state.body);["like","cheer","congrats","expect","surprise","sad"].forEach(key=>set("react_"+key,state.reactions[key]));set("commentTotal",state.commentTotal);set("commentActive",state.commentActive);set("commentDeleted",state.commentDeleted);set("commentViolation",state.commentViolation);if(typeof renderCommentsEditor==="function")renderCommentsEditor();if(typeof setView==="function")setView(state.view||"mobile");}
bindInput("title","title");bindInput("date","date");bindInput("time","time");bindInput("likeCount","likeCount");bindInput("commentCount","commentCount");bindInput("body","body");
["like","cheer","congrats","expect","surprise","sad"].forEach(key=>{const el=document.getElementById("react_"+key);if(el)el.addEventListener("input",e=>{state.reactions[key]=e.target.value;renderAll();});});
bindInput("commentTotal","commentTotal");bindInput("commentActive","commentActive");bindInput("commentDeleted","commentDeleted");bindInput("commentViolation","commentViolation");
function renderCommentsEditor(){const wrap=document.getElementById("commentsEditor");if(!wrap)return;wrap.innerHTML=state.comments.map((c,i)=>`<div class="comment-edit-card" data-comment-card="${i}"><div class="field"><label>작성자 프로필 사진</label><div class="comment-edit-avatar-row"><img class="comment-edit-avatar-preview" src="${c.avatar||PLACEHOLDER_AVATAR}" /><input type="file" accept="image/*" data-comment-field="avatar" data-comment-index="${i}" /></div></div><div class="field"><label>작성자 이름</label><input type="text" value="${String(c.nick||"").replace(/"/g,'&quot;')}" data-comment-field="nick" data-comment-index="${i}" /></div><div class="field"><label>댓글 단 시간</label><input type="text" value="${String(c.date||"").replace(/"/g,'&quot;')}" placeholder="예: 2026.09.07. 11:23" data-comment-field="date" data-comment-index="${i}" /></div><div class="field"><label>내용</label><textarea rows="3" data-comment-field="body" data-comment-index="${i}">${c.body||""}</textarea></div><button type="button" class="comment-edit-remove" data-comment-remove="${i}">이 댓글 삭제</button></div>`).join("");}
const addCommentBtn=document.getElementById("addCommentBtn");if(addCommentBtn)addCommentBtn.addEventListener("click",()=>{state.comments.push({avatar:null,nick:"user****",date:"",body:"",image:null,likes:"0"});renderCommentsEditor();renderAll();});
const commentsEditor=document.getElementById("commentsEditor");if(commentsEditor){commentsEditor.addEventListener("input",e=>{const field=e.target.getAttribute("data-comment-field"),idx=e.target.getAttribute("data-comment-index");if(field&&idx!==null&&field!=="avatar"&&field!=="image"){state.comments[idx][field]=e.target.value;renderAll();}});commentsEditor.addEventListener("change",e=>{const field=e.target.getAttribute("data-comment-field"),idx=e.target.getAttribute("data-comment-index");if((field==="avatar"||field==="image")&&idx!==null){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{state.comments[idx][field]=ev.target.result;renderCommentsEditor();renderAll();};reader.readAsDataURL(file);}});commentsEditor.addEventListener("click",e=>{const removeIdx=e.target.getAttribute("data-comment-remove");if(removeIdx!==null){state.comments.splice(removeIdx,1);renderCommentsEditor();renderAll();}});}
document.addEventListener("click",e=>{if(e.target.matches("[data-extra-toggle]")){state.extraOpen=!state.extraOpen;renderExtraToggle();saveState();}});
function bindFileInput(inputId,key,previewId){const input=document.getElementById(inputId);if(!input)return;input.addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{state[key]=ev.target.result;const preview=document.getElementById(previewId);if(preview)preview.src=ev.target.result;renderAll();};reader.readAsDataURL(file);});}
bindFileInput("outletLogo","outletLogo","outletLogoPreview");bindFileInput("articleImage","img","articleImagePreview");
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{fillFormFromState();renderAll();});else{fillFormFromState();renderAll();}

// 네이버 고정 텍스트 및 편집 대상 정리
(function(){
 const q=id=>document.getElementById(id), c=q('naverCanvas'), panel=document.querySelector('#naverApp .naver-settings');
 if(!c||!panel)return;
 const fixed={nvSearchOut:{left:591,top:133,fontSize:28},nvAccountNameOut:{left:1517,top:390,fontSize:22,fontWeight:700,letterSpacing:-0.5},nvEmailOut:{left:1517,top:428},nvHeadlinesOut:{left:684,top:593,fontSize:25,fontWeight:430,letterSpacing:-2,lineHeight:2},nvFeatureTitle:{left:345,top:821,fontSize:22,fontWeight:520,letterSpacing:-0.5,lineHeight:1.35},nvFeatureMeta:{left:401,top:552,fontSize:22,fontWeight:400,letterSpacing:-1}};
 const applyFixed=(id,st)=>{const e=q(id);if(!e)return;for(const [k,v] of Object.entries(st))e.style.setProperty(k,typeof v==='number'&&['left','top','fontSize'].includes(k)?v+'px':typeof v==='number'&&k==='letterSpacing'?v+'px':k==='fontWeight'?String(v):k==='lineHeight'?String(v):String(v),'important');e.classList.add('nv-fixed-text');};
 Object.entries(fixed).forEach(([id,st])=>applyFixed(id,st));
 const contentMap={nvSearch:'nvSearchOut',nvAccountName:'nvAccountNameOut',nvEmail:'nvEmailOut',nvFeatureTitleInput:'nvFeatureTitle',nvFeatureMetaInput:'nvFeatureMeta'};
 Object.entries(contentMap).forEach(([iid,oid])=>{const a=q(iid),b=q(oid);if(!a||!b)return;const sync=()=>{b.textContent=a.value;applyFixed(oid,fixed[oid]);};a.addEventListener('input',sync);sync();});
 // 중요: 고정 요소의 style/class를 MutationObserver로 감시하지 않습니다.
 // 이전 코드는 applyFixed()가 style/class를 바꾸면 다시 observer가 실행되는 무한 루프를 만들었습니다.
 const editors=panel.querySelectorAll('.nv-single-editor');editors.forEach((e,i)=>{if(i>0)e.remove();});
 const box=q('nvDirectEditorFinal');
 if(box){const sel=q('nvFinalTarget');if(sel){const fixedIds=new Set(Object.keys(fixed));[...sel.options].forEach(o=>{if(fixedIds.has(o.value))o.remove();});const allowed=new Set(['nvRightTextOut','nvNewsbarMiddle','nvPressEditable1','nvPressEditable2','nvPressEditable3','nvPressEditable4','nvSubscribedOverlay','nvOtherNewsOverlay']);[...sel.options].forEach(o=>{if(o.value&&!allowed.has(o.value))o.remove();});}const help=box.querySelector('.nv-f-help');if(help)help.textContent='오른쪽 패널에서 선택한 항목만 위치와 스타일을 수정할 수 있습니다. 프로필/검색어/이메일/대표뉴스/뉴스목록/기사 날짜·출처는 고정입니다.';}
 const mid=q('nvNewsbarMiddle'),midIn=q('nvNewsbarMiddleInput');if(mid){mid.classList.remove('nv-fixed-text');mid.style.setProperty('display','block','important');mid.style.setProperty('position','absolute','important');mid.style.setProperty('left','285px','important');mid.style.setProperty('top','465px','important');mid.style.setProperty('z-index','40','important');mid.style.setProperty('pointer-events','none','important');mid.style.setProperty('white-space','nowrap','important');}if(mid&&midIn){const sync=()=>{mid.textContent=midIn.value;mid.classList.remove('nv-fixed-text');mid.style.setProperty('display','block','important');};midIn.addEventListener('input',sync);sync();}
 let layer=q('nvPressEditableLayer');if(!layer){layer=document.createElement('div');layer.id='nvPressEditableLayer';c.appendChild(layer);}layer.style.cssText='position:absolute;inset:0;z-index:40;pointer-events:none;';
 for(let i=1;i<=4;i++){let out=q('nvPressEditable'+i);if(!out){out=document.createElement('div');out.id='nvPressEditable'+i;layer.appendChild(out);}}
})();
